/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{html,ts}",
  ],
  theme: {
    extend: {},

    colors:{
      transparent: 'transparent',
      current: 'currentColor',
      'white': '#ffffff',
      'purple': '#3f3cbb',
      'midnight': '#121063',
      'metal': '#565584',
      'tahiti': '#3ab7bf',
      'silver': '#ecebff',
      'bubble-gum': '#ff77e9',
      'bermuda': '#78dcca',
      'green-dark': '#597445',
      'sky-blue': '#87CEEB',
      'midnight-blue': '#191970',
      'sunset-orange': '#FF4500',
      'forest-green': '#228B22',
      'lavender': '#E6E6FA',
      'charcoal': '#36454F',
      'cream': '#FFFDD0',
      'burgundy': '#800020',
      'coral': '#FF7F50',
      'gold': '#FFD700',
      'teal': '#008080',
      'plum': '#DDA0DD',
      'olive': '#808000',
      'peach': '#FFDAB9',
      'slate': '#708090',
      'aqua': '#00FFFF',
      'brick-red': '#CB4154',
      'sea-green': '#2E8B57',
      'ivory': '#FFFFF0',
      'navy': '#000080',
      'pink': '#FFC0CB',
      'amber': '#FFBF00',
      'sapphire': '#0F52BA',
      'lime': '#BFFF00',
      'violet': '#8F00FF',
      'crimson': '#DC143C',
      'cerulean': '#007BA7',
      'salmon': '#FA8072',
      
    }
  },
  plugins: [],
}